package com.model.structure.power;

import com.GameConstant.ModelConstants;
import com.model.Model;


/**
 * @brief define a coal plant 
 * @author ang3d
 *
 */
public class CoalPlant extends PowerPlant {
	
	//constructor
	public CoalPlant(int X, int Y, String type, int index) {
		super(X, Y, type);
		
		this.capacity = ModelConstants.CAPACITY_COALPLANT;
		this.name = "C" + index;
		this.tenants = 0;
	
	}
	
	//*********************************
	//Public overridden method
	//*********************************
	
	//return the production of this plant if it is working 
	@Override
	public float getProd(Model game) {
		
		if(isWorking) {
			return this.production = ModelConstants.PRODUCTIVITY_COALPLANT * this.tenants;
		}
		return 0;
		
	}
	
	//return the pollution generated by this plant
	@Override
	public float getPollution() {
		
		return ModelConstants.POLLUTION_COALPLANT;
	}
	
	
	
	
}
