package com.model.structure.power;

import com.GameConstant.ModelConstants;
import com.model.Model;

/**
 * @brief define a nuclear plant
 * @author ang3d
 *
 */
public class Nuclear extends PowerPlant{

	public Nuclear(int X, int Y, String type, int index) {
		super(X, Y, type);
		this.name = ("");
		this.capacity = ModelConstants.CAPACITY_NUCLEAR;
		this.name = "N" + index;
		this.tenants = 0;
		
	}

	
	
	//**********************************
	//Public overridden methods
	//**********************************
	
	//method that return the production of the plant (0 if it is not working)
	@Override
	public float getProd(Model game) {
		
		if(isWorking) {
			return this.production = ModelConstants.PRODUCTIVITY_NUCLEAR * this.tenants;
		}
		
		return 0;
	}
	
	//method that return the pollution generated by the plant 
	@Override
	public float getPollution() {
		
		return ModelConstants.POLLUTION_NUCLEAR;
	}
	
	
	
}
